# Generated by Django 4.0.3 on 2022-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_adopt_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='image',
            field=models.ImageField(default='dog', upload_to='ecomerce/adopt_img'),
            preserve_default=False,
        ),
    ]
