# Generated by Django 4.0.3 on 2022-10-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_adopt_contact_info_adopt_good_with_dogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='good_with_dogs',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='good_with_kids',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='needs_loving_adopter',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='neutered_or_spayed',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='shots_upto_date',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='vacinated',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1),
        ),
    ]
