# Generated by Django 4.0.3 on 2022-10-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_adopt_good_with_dogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='contact_info',
            field=models.IntegerField(default='987654321', max_length=10),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='good_with_dogs',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='good_with_kids',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='needs_loving_adopter',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='neutered_or_spayed',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='shots_upto_date',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='vacinated',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1),
        ),
    ]
