# Generated by Django 4.0.3 on 2022-10-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_adopt_age_alter_adopt_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='neutered_or_spayed',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1),
        ),
    ]
