# Generated by Django 4.0.3 on 2022-10-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_adopt_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecomerce/adopt_img'),
        ),
    ]
