# Generated by Django 4.0.3 on 2022-10-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_adopt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('responsibilty', models.CharField(max_length=100)),
                ('scaretaker', models.CharField(max_length=100)),
                ('lalone', models.CharField(max_length=100)),
                ('firstime', models.CharField(max_length=100)),
                ('petname', models.CharField(max_length=100)),
            ],
        ),
    ]
