# Generated by Django 4.0.3 on 2022-11-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_adopt_vaccineinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='is_available',
            field=models.CharField(choices=[('y', 'Yes'), ('in', 'Inprocess'), ('n', 'No')], default='y', max_length=2),
        ),
    ]
