# Generated by Django 4.0.3 on 2022-11-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_adopt_image_alter_adopt_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecomerce/adopt_img'),
        ),
    ]
