# Generated by Django 4.0.3 on 2022-11-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_adopt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecomerce/adopt_img/'),
        ),
    ]
