# Generated by Django 4.0.3 on 2022-11-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_adopt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('forreq', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('detailedreq', models.CharField(max_length=1000)),
                ('contact_info', models.IntegerField(default='987654321')),
            ],
        ),
    ]
