# Generated by Django 4.0.3 on 2022-11-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_services_serviceresponses_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceresponses',
            name='detailedreq',
        ),
    ]
