# Generated by Django 4.0.3 on 2022-11-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_serviceresponses_detailedreq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceresponses',
            name='forreq',
        ),
        migrations.AddField(
            model_name='serviceresponses',
            name='detailedreq',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
