# Generated by Django 4.0.3 on 2022-11-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_serviceresponses_forreq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresponses',
            name='detailedreq',
            field=models.CharField(max_length=1000),
        ),
    ]
