# Generated by Django 4.0.3 on 2022-11-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_serviceresponses_detailedreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresponses',
            name='service',
            field=models.CharField(default='987654321', max_length=100),
        ),
    ]
