# Generated by Django 4.0.3 on 2022-11-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_serviceresponses_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresponses',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
