# Generated by Django 4.0.3 on 2022-11-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_serviceresponses_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresponses',
            name='subject',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
