# Generated by Django 4.0.3 on 2022-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_serviceresponses_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceresponses',
            name='contact_info',
            field=models.CharField(default='987654321', max_length=100),
        ),
    ]
